{
  "special_tokens": {
    "think_start": 151667,
    "think_end": 151668
  },
  "quick": {
    "model_name": "Qwen3Guard-Gen-8B",
    "model_path": "/mnt/shared-storage-user/yangxuqing/models/Qwen3Guard-Gen-8B",
    "param": "8",
    "mem_fraction_static": 0.15
  },
  "reference": {
    "model_name": "Qwen3Guard-Gen-8B",
    "model_path": "/mnt/shared-storage-user/yangxuqing/models/Qwen3Guard-Gen-8B",
    "param": "8",
    "mem_fraction_static": 0.20
  },
  "continuation_main": {
    "model_name": "Qwen3Guard-Gen-8B",
    "model_path": "/mnt/shared-storage-user/yangxuqing/models/Qwen3Guard-Gen-8B",
    "param": "8",
    "tp_size": 1,
    "base_gpu_id": 0,
    "mem_fraction_static": 0.90
  },
  "continuation_reference": {
    "model_name": "Qwen3Guard-Gen-8B",
    "model_path": "/mnt/shared-storage-user/yangxuqing/models/Qwen3Guard-Gen-8B",
    "param": "8",
    "tp_size": 1,
    "base_gpu_id": 0,
    "mem_fraction_static": 0.90
  },
  "verify": {
    "model_name": "Qwen3-32B",
    "model_path": "/mnt/shared-storage-user/yangxuqing/models/Qwen3-32B/snapshots/9216db5781bf21249d130ec9da846c4624c16137",
    "mem_fraction_static": 0.90,
    "max_new_tokens": 1024,
    "base_gpu_id": 0,
    "tp_size": 1,
    "apply_chat_template_kwargs": {
      "enable_thinking": false
    }
  },
  "router": {
    "router_name": "Qwen3-0.6B+Qwen3Guard-stream-8B",
    "router_path": "/mnt/shared-storage-user/yangxuqing/R2R/Routers/R2R_router/Qwen3-0.6B+Qwen3-8B/default_router.pt",
    "switching_strategy": "entropy",
    "entropy_threshold": 0.5,
  }
}
